name: Horusec Scan

on: [push, workflow_dispatch]

jobs:
  checking_code:
    runs-on: ubuntu-latest
    name: Horusec Scan
    steps:
      - name: Checkout 
        uses: actions/checkout@v2.3.4
      - run: |
          touch horusec-config.json
          echo [] >> horusec-config.json
      - run: cat horusec-config.json
      - name: Run Horusec
        id: run_horusec
        uses: GuillaumeFalourd/horusec-action@main
        with:
          arguments: -p="./" --ignore="**/.vscode/**, **/*.env, **/.mypy_cache/**, **/tests/**"
        

